import Head from 'next/head'
import Image from 'next/image'
import NavigationBar from '../components/NavigationBar/Navigationbar'
import ProfileDetails from '../components/ProfileDetails/ProfileDetails'
import styles from '../styles/Home.module.css'
import { parseCookies } from 'nookies'
import axios from 'axios'
import { useRouter } from 'next/router'


const MainPage = ({ userData }: { userData: any }) => {
  const router = useRouter();

  const jwt = parseCookies().jwt;

  const { id, username, email, full_name, description, phone, avatar } = userData;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <section>
        <ProfileDetails
          id={id}
          username={username}
          email={email}
          full_name={full_name}
          description={description}
          phone={phone}
          avatar={avatar} />
        <NavigationBar />
      </section>


      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Team4Life{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


export async function getServerSideProps(ctx: any) {
  const jwt = parseCookies(ctx).jwt;

  const res = await axios.get("http://localhost:1337/api/users/me", {
    headers: {
      Authorization: `Bearer ${jwt}`
    }
  })
  const userData = await res.data;
  console.log(userData)


  return {
    props: {
      userData
    }
  }
}


export default MainPage
